dwm-condominios/Controllers/CondominoController.cs
using App_Dominio.Controllers;
using App_Dominio.Security;
using DWM.Models.Enumeracoes;
using DWM.Models.Persistence;
using DWM.Models.Repositories;
using System.Web.Mvc;
using DWM.Models.Entidades;
using App_Dominio.Entidades;
using App_Dominio.Pattern;
using DWM.Models.BI;
using System;
using App_Dominio.Enumeracoes;
using DWM.Models.Pattern;
using System.Collections.Generic;
using App_Dominio.Models;
using System.Web;
using System.Linq;
using System.IO;
using System.Web.Helpers;
using App_Dominio.Repositories;

namespace DWM.Controllers
{
    public class CondominoController : DwmRootController<CondominoUnidadeViewModel, CondominoUnidadeModel, ApplicationContext>
    {
        private int _avatarWidth = 100; // ToDo - Change the size of the stored avatar image
        private int _avatarHeight = 100; // ToDo - Change the size of the stored avatar image

        #region Inheritance
        public override int _sistema_id() { return (int)DWM.Models.Enumeracoes.Sistema.DWMCONDOMINIOS; }

        public override string getListName()
        {
            return "Listar";
        }

        #region List
        public override ActionResult List(int? index, int? pageSize = 25, string descricao = null)
        {
            return ListParam(index, 25, Request["EdificacaoID"], Request["UnidadeID"], descricao);
        }

        [AuthorizeFilter]
        public ActionResult ListParam(int? index, int? pageSize = 25, string EdificacaoID = null, string UnidadeID = null, string Nome = null)
        {
            ViewBag.ValidateRequest = true;
            if (ViewBag.ValidateRequest)
            {
                ViewBag.TipoEdificacao = DWMSessaoLocal.GetTipoEdificacao(null).Descricao;
                int _EdificacaoID = EdificacaoID == null || EdificacaoID == "" ? 0 : int.Parse(EdificacaoID);
                int _UnidadeID = UnidadeID == null || UnidadeID == "" ? 0 : int.Parse(UnidadeID);

                EmpresaSecurity<SecurityContext> security = new EmpresaSecurity<SecurityContext>();
                Sessao sessaoCorrente = security.getSessaoCorrente();
                SessaoLocal SessaoLocal = DWMSessaoLocal.GetSessaoLocal();

                ViewBag.empresaId = sessaoCorrente.empresaId;
                ViewBag.CondominoID = SessaoLocal.CondominoID;

                ListViewCondominoUnidade l = new ListViewCondominoUnidade();
                if (SessaoLocal.CondominoID == 0)
                    return this._List(index, pageSize, "Browse", l, _EdificacaoID, _UnidadeID, Nome);
                else
                    return this._List(index, pageSize, "Browse", l, SessaoLocal.CondominoID);
            }
            else
                return View();
        }

        [AuthorizeFilter]
        public ActionResult ListDesativados(int? index, int? pageSize = 25, string EdificacaoID = null, string UnidadeID = null, string Nome = null)
        {
            ViewBag.ValidateRequest = true;
            if (ViewBag.ValidateRequest)
            {
                int _EdificacaoID = EdificacaoID == null || EdificacaoID == "" ? 0 : int.Parse(EdificacaoID);
                int _UnidadeID = UnidadeID == null || UnidadeID == "" ? 0 : int.Parse(UnidadeID);

                EmpresaSecurity<SecurityContext> security = new EmpresaSecurity<SecurityContext>();
                Sessao sessaoCorrente = security.getSessaoCorrente();
                SessaoLocal SessaoLocal = DWMSessaoLocal.GetSessaoLocal();

                ViewBag.empresaId = sessaoCorrente.empresaId;
                ViewBag.CondominoID = SessaoLocal.CondominoID;

                ListViewCondominosDesativados l = new ListViewCondominosDesativados();
                if (SessaoLocal.CondominoID == 0)
                    return this._List(index, pageSize, "Browse", l, _EdificacaoID, _UnidadeID, Nome);
                else
                    return this._List(index, pageSize, "Browse", l, SessaoLocal.CondominoID);
            }
            else
                return View();
        }

        [AuthorizeFilter]
        public ActionResult ListInativos()
        {
            if (ViewBag.ValidateRequest)
            {
                ViewBag.TipoEdificacao = DWMSessaoLocal.GetTipoEdificacao(null).Descricao;
                BindBreadCrumb("Condômino", ClearBreadCrumbOnBrowse());
                ListViewCondominosInativos l = new ListViewCondominosInativos();
                return this._List(0, 1000, "Browse", l);
            }
            else
                return View();
        }

        /// <summary>
        /// Este método é acionado pelo funcionalidade CHAMADO
        /// </summary>
        /// <param name="index"></param>
        /// <param name="pageSize"></param>
        /// <param name="EdificacaoID"></param>
        /// <param name="UnidadeID"></param>
        /// <param name="Nome"></param>
        /// <returns></returns>
        public ActionResult ListCondomino(int? index, int? pageSize = 25, string EdificacaoID = null, string UnidadeID = null, string Nome = null)
        {
            ViewBag.ValidateRequest = true;
            if (ViewBag.ValidateRequest)
            {
                ViewBag.TipoEdificacao = DWMSessaoLocal.GetTipoEdificacao(null).Descricao;
                int _EdificacaoID = EdificacaoID == null || EdificacaoID == "" ? 0 : int.Parse(EdificacaoID);
                int _UnidadeID = UnidadeID == null || UnidadeID == "" ? 0 : int.Parse(UnidadeID);
                ViewBag.TipoEdificacao = DWMSessaoLocal.GetTipoEdificacao(null).Descricao;

                EmpresaSecurity<SecurityContext> security = new EmpresaSecurity<SecurityContext>();
                Sessao sessaoCorrente = security.getSessaoCorrente();
                SessaoLocal SessaoLocal = DWMSessaoLocal.GetSessaoLocal();

                ViewBag.empresaId = security.getSessaoCorrente().empresaId;

                ListViewCondominoUnidadeChamado l = new ListViewCondominoUnidadeChamado();

                if (SessaoLocal.CondominoID == 0)
                    return this._List(index, pageSize, "Browse", l, _EdificacaoID, _UnidadeID, Nome);
                else
                    return this._List(index, pageSize, "Browse", l, SessaoLocal.CondominoID);
            }
            else
                return View();
        }
        #endregion

        #endregion

        #region Index
        [AuthorizeFilter]
        public ActionResult Index(int id, int EdificacaoID, int UnidadeID, string TipoPessoa)
        {
            if (ViewBag.ValidateRequest)
            {
                //BindBreadCrumb(getListName(), ClearBreadCrumbOnBrowse());

                BindBreadCrumb(getBreadCrumbText("Condômino", null));

                SessaoLocal s = DWMSessaoLocal.GetSessaoLocal();
                ViewBag.SessaoLocal = s;

                Factory<CondominoEditViewModel, ApplicationContext> factory = new Factory<CondominoEditViewModel, ApplicationContext>();
                CondominoEditViewModel value = new CondominoEditViewModel()
                {
                    UnidadeViewModel = new UnidadeViewModel()
                    {
                        EdificacaoID = EdificacaoID,
                        UnidadeID = UnidadeID,
                    },
                    CredenciadoViewModel = new CredenciadoViewModel()
                    {
                        CondominoID = id,
                    }
                };
                if (TipoPessoa == "PF")
                    value.CondominoViewModel = new CondominoPFViewModel()
                    {
                        CondominoID = id,
                    };
                else
                    value.CondominoViewModel = new CondominoPJViewModel()
                    {
                        CondominoID = id,
                    };

                CondominoEditViewModel obj = factory.Execute(new EditarCondominoBI(), value);
                if (obj.CondominoViewModel.mensagem.Code > 0)
                    obj = null;
                    
                return View(obj);
            }
            return View();
        }

        [AuthorizeFilter]
        public ActionResult EditCondomino(int CondominioID, int CondominoID, string Nome, string Email, string IndFiscal, string DataCadastro,
                                            string IndSituacao, string TelParticular1, string TelParticular2, string DataNascimento, string usuarioId,
                                            string Sexo, string IndProprietario, string IndAnimal, string ProfissaoID, string Observacao, 
                                            string cnpj, string Administrador, string RamoAtividadeID)
        {
            if (ViewBag.ValidateRequest)
            {
                CondominoViewModel result = null;
                try
                {
                    SessaoLocal s = DWMSessaoLocal.GetSessaoLocal();
                    ViewBag.SessaoLocal = s;
                    CondominoViewModel value = null;

                    if (IndFiscal != null && IndFiscal.Trim().Length > 0)
                    {
                        value = new CondominoPFViewModel()
                        {
                            CondominioID = CondominioID,
                            CondominoID = CondominoID,
                            Nome = Nome,
                            Email = Email,
                            IndFiscal = IndFiscal,
                            IndSituacao = IndSituacao,
                            DataCadastro = DataCadastro != null && DataCadastro != "" ? Funcoes.StringToDate(DataCadastro).Value : Funcoes.Brasilia(),
                            TelParticular1 = TelParticular1,
                            TelParticular2 = TelParticular2,
                            Sexo = Sexo,
                            IndProprietario = IndProprietario,
                            IndAnimal = IndAnimal,
                            DataNascimento = Funcoes.StringToDate(DataNascimento),

dwm-condominios/Controllers/DocumentosController.cs
using App_Dominio.Controllers;
using App_Dominio.Entidades;
using App_Dominio.Models;
using App_Dominio.Security;
using DWM.Models.Entidades;
using DWM.Models.Enumeracoes;
using DWM.Models.Persistence;
using DWM.Models.Repositories;
using System;
using System.Web.Mvc;

namespace DWM.Controllers
{
    public class DocumentosController : DwmRootController<ArquivoViewModel, ArquivoModel, DWM.Models.Entidades.ApplicationContext>
    {
        #region inheritance
        public override int _sistema_id() { return (int)DWM.Models.Enumeracoes.Sistema.DWMCONDOMINIOS; }
        public override string getListName()
        {
            return "Listar";
        }
        #endregion

        #region List
        [AuthorizeFilter]
        public override ActionResult List(int? index, int? pageSize = 50, string descricao = null)
        {
            return ListParam(index, 25, Request["data1"], Request["data2"], 
                                Request["EdificacaoID"], Request["UnidadeID"], 
                                Request["CondominoID"], Request["GrupoCondominoID"], descricao);
        }

        [AuthorizeFilter]
        public ActionResult ListParam(int? index, int? pageSize = 25, 
                                        string data1 = null, string data2 = null, 
                                        string EdificacaoID = null, string UnidadeID = null, string CondominoID = null,
                                        string GrupoCondominoID = null,
                                        string Nome = null)
        {
            if (ViewBag.ValidateRequest)
            {
                ListViewArquivo l = new ListViewArquivo();
                return _ListParam(l, index, pageSize, data1, data2, EdificacaoID, UnidadeID, CondominoID, GrupoCondominoID, Nome);
            }
            else
                return View();
        }

        [AuthorizeFilter]
        public ActionResult ListParamHome(int? index, int? pageSize = 12,
                                        string data1 = null, string data2 = null,
                                        string EdificacaoID = null, string UnidadeID = null, string CondominoID = null,
                                        string GrupoCondominoID = null,
                                        string Nome = null)
        {
            ViewBag.ValidateRequest = true;
            if (ViewBag.ValidateRequest)
            {
                ListViewArquivoHome l = new ListViewArquivoHome();
                return _ListParam(l, index, pageSize, data1, data2, EdificacaoID, UnidadeID, CondominoID, GrupoCondominoID, Nome);
            }
            else
                return View();
        }

        private ActionResult _ListParam(ListViewModelLocal<ArquivoViewModel> list, 
                                        int? index, int? pageSize = 12,
                                        string data1 = null, string data2 = null,
                                        string EdificacaoID = null, string UnidadeID = null, string CondominoID = null,
                                        string GrupoCondominoID = null,
                                        string Nome = null)
        {
            DateTime _data1 = data1 == null || data1 == "" ? Funcoes.Brasilia().AddMonths(-3) : Funcoes.StringToDate(data1).Value;
            DateTime _data2 = data2 == null || data2 == "" ? Funcoes.Brasilia().Date.AddDays(1).AddMinutes(-1) : Funcoes.StringToDate(data2).Value.Date.AddDays(1).AddMinutes(-1);
            int _EdificacaoID = EdificacaoID == null || EdificacaoID == "" ? 0 : int.Parse(EdificacaoID);
            int _UnidadeID = UnidadeID == null || UnidadeID == "" ? 0 : int.Parse(UnidadeID);
            int _CondominoID = CondominoID == null || CondominoID == "" ? 0 : int.Parse(CondominoID);
            int _GrupoCondominoID = GrupoCondominoID == null || GrupoCondominoID == "" ? 0 : int.Parse(GrupoCondominoID);

            EmpresaSecurity<SecurityContext> security = new EmpresaSecurity<SecurityContext>();
            Sessao sessaoCorrente = security.getSessaoCorrente();
            SessaoLocal SessaoLocal = DWMSessaoLocal.GetSessaoLocal();

            ViewBag.empresaId = sessaoCorrente.empresaId;
            ViewBag.CondominoID = SessaoLocal.CondominoID;

            if (SessaoLocal.CondominoID == 0)
                return this._List(index, pageSize, "Browse", list, _data1, _data2, _EdificacaoID, _UnidadeID, _CondominoID, _GrupoCondominoID, Nome);
            else
                return this._List(index, pageSize, "Browse", list, _data1, _data2, _EdificacaoID, _UnidadeID, SessaoLocal.CondominoID, _GrupoCondominoID, Nome);
        }

        #endregion

        #region Edit
        [AuthorizeFilter]
        public ActionResult Edit(string FileID)
        {
            return _Edit(new ArquivoViewModel() { FileID = FileID });
        }
        #endregion

        #region Delete
        [AuthorizeFilter]
        public ActionResult Delete(string FileID)
        {
            return _Edit(new ArquivoViewModel() { FileID = FileID });
        }
        #endregion

        #region Retorno as Unidades de uma dada Edificação
        [AllowAnonymous]
        public JsonResult GetNames(string term, int tag)
        {
            var results = new BindDropDownList().Unidades("Selecione...", "", term, tag);

            return new JsonResult()
            {
                Data = results,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };

        }
        #endregion
    }
}

dwm-condominios/Views/Documentos/Browse.cshtml
@using App_Dominio.Repositories
@using DWM.Models.Repositories
@model PagedList<ArquivoViewModel>
@{
    TransacaoRepository[] t = { new TransacaoRepository(), new TransacaoRepository() };
    t[0].url = "../Documentos/Create";
    t[0].nomeCurto = "Incluir";
    t[0].referencia = "";
    t[0].exibir = "S";

    t[1].url = "../Home/Default";
}
@if (Model != null)
{
    <div class="container-cadastro">
        <div class="x_panel">
            @Html.EditorFor(info => Model, "FORMULARIO", new { Brand = "Documentos", Descricao = "", Transacao = t })
            <div class="x_content">
                @if ((int)ViewBag.CondominoID == 0)
                {
                    using (Ajax.BeginForm("ListParam", "Condomino", new AjaxOptions { HttpMethod = "get", UpdateTargetId = "div-download" }, new { @role = "search", @id = "form0" }))
                    {
                        @*@Html.Partial("_alerts")*@
                        @Html.ValidationSummary("", new { @class = "text-danger" })
                        @Html.Hidden("CondominioID", (int)ViewBag.empresaId)
                        <div class="row">
                            <div class="col-md-6 col-xs-12 col-sm-12">
                                <div class="form-group">
                                    <label class="control-label">Arquivo</label>
                                    <div class="input-group col-md-12">
                                        <input type="text" id="Nome" name="Nome" class="form-control" maxlength="40" placeholder="Informar o nome do arquivo (opcional)" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3 col-xs-12 col-sm-12">
                                <div class="form-group">
                                    @Edificacao.Bloco(0)
                                    @Html.DropDownList("EdificacaoID", new DWM.Models.Enumeracoes.BindDropDownList().Edificacoes("Selecione...", "", (int)ViewBag.empresaId), new { @class = "form-control", @onchange = "GetSelectListOnCascade('EdificacaoID','UnidadeID', 'CondominioID')" })
                                </div>
                            </div>
                            <div class="col-md-3 col-xs-12 col-sm-12">
                                <div class="form-group">
                                    <label class="control-label">Unidade</label>
                                    @Html.DropDownList("UnidadeID", new DWM.Models.Enumeracoes.BindDropDownList().Unidades("Selecione...", "", 0, (int)ViewBag.empresaId), new { @class = "form-control" })
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4 col-lg-4 col-xs-12 col-sm-12">
                                <div class="form-group">
                                    <label class="control-label">Grupo/Condômino</label>
                                    @Html.DropDownList("GrupoCondominoID", new DWM.Models.Enumeracoes.BindDropDownList().GrupoCondominos("Todos...", "", (int)ViewBag.empresaId), new { @class = "form-control" })
                                </div>
                            </div>
                        </div>
                        <input type="button" class="btn btn-primary" value="Buscar" onclick="Refresh(0, 25, '@Model.action', '@Model.DivId')" />
                        <input type="button" onclick="window.location = '../Documentos/Create'" class="btn btn-default" value="Incluir" />
                        <br />
                    }
                }
                <div id="div-download">
                    @if (Model != null && Model.Count() > 0)
                    {
                        @Html.Partial("ListParam", Model)
                    }
                </div>
            </div>
        </div>
    </div>
}
else
{
    @Html.Partial("_AcessoNegadoModal")
}

<script>
    $(function () {
        $('#form0').submit(function () {
            if ($(this).valid()) {
                $.ajax({
                    url: this.action,
                    type: this.method,
                    data: $(this).serialize(),
                    success: function (result) {
                        $('#div-download').html(result);
                    }
                });
            }
            return false;
        });
    });
</script>

dwm-condominios/Views/Documentos/Create.cshtml
@using App_Dominio.Repositories
@using App_Dominio.Enumeracoes
@model DWM.Models.Repositories.ArquivoViewModel
@{
    TransacaoRepository[] t = { new TransacaoRepository(), new TransacaoRepository() };
    t[0].url = "../Documentos/Browse";
    t[0].nomeCurto = "Listar";
    t[0].referencia = "";

    t[1].url = "../Home/Default";

    var path = Model.Path();
}

<div class="container-cadastro">
    @Html.Partial("_alerts")
    <div class="x_panel">
        @Html.EditorFor(info => Model, "FORMULARIO", new { Brand = "Documentos", Descricao = "Enviar arquivos para a nuvem", Transacao = t })
        <div class="x_content">
            @using (Html.BeginForm("Create", "Documentos", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data" }))
            {
                @Html.HiddenFor(info => info.CondominioID)
                <div class="row">
                    <div class="col-md-3 col-xs-12 col-sm-12">
                        <div class="form-group">
                            @*<label class="control-label">Edificação</label>*@
                            @Edificacao.Bloco(Model.empresaId)
                            @Html.DropDownList("EdificacaoID", new DWM.Models.Enumeracoes.BindDropDownList().Edificacoes("Selecione...", "", Model.empresaId), new { @class = "form-control", @onchange = "GetSelectListOnCascade('EdificacaoID','UnidadeID', 'CondominioID')" })
                        </div>
                    </div>
                    <div class="col-md-3 col-xs-12 col-sm-12">
                        <div class="form-group">
                            <label class="control-label">Unidade</label>
                            @Html.DropDownList("UnidadeID", new DWM.Models.Enumeracoes.BindDropDownList().Unidades("Selecione...", "", 0, Model.empresaId), new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="col-md-3 col-lg-3 col-xs-12 col-sm-12">
                        <div class="form-group">
                            <label class="control-label">Grupo/Condômino</label>
                            @Html.DropDownList("GrupoCondominoID", new DWM.Models.Enumeracoes.BindDropDownList().GrupoCondominos("Todos...", "", Model.empresaId), new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="col-md-3 col-lg-3 col-xs-12 col-sm-12">
                        <div class="form-group">
                            <label class="control-label">Sempre visível</label>
                            @Html.DropDownList("IndSempreVisivel", DropDownListEnum.SimNao(Model.IndSempreVisivel), new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 col-xs-12 col-sm-12">
                        <div class="form-group">
                            <label class="control-label">Nome do documento</label>
                            <div class="input-group col-md-12">
                                <input type="text" id="Nome" name="Nome" class="form-control" value="@Model.Nome" maxlength="40" placeholder="Informar o nome do Documento" />
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12">
                        <label class="control-label">Arquivo</label><br />
                        <div class="form-group">
                            <input id="fileupload" type="file" name="files1[]">
                            @Html.Hidden("FileID")
                            @Html.Hidden("NomeOriginal1")
                        </div>
                        <div class="file_name" id="file_name1"></div>
                        <div class="progress" id="progress1">
                            <div id="progress1-bar" class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                                <span class="sr-only">0% complete</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="ln_solid"></div>
                <div class="row clearfix">
                    <div class="col-md-12">
                        <div class="form-group">
                            <input type="submit" class="btn btn-success" value="Salvar" name="btn-salvar" id="btn-salvar" />
                            <input type="button" onclick="window.location = '../Documentos/Browse'" class="btn btn-default" value="Cancelar" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<!-- Model Anexos -->
<div id="myModal1" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
    <div class="modal-dialog modal-lg">
        <div class="modal-content hidden-xs">
            <div class="modal-header bg-primary">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true" id="btnModal">×</button>
                <h3 class="modal-title" id="myModalLabel">Modal title</h3>
            </div>
            <div class="modal-body" id="myModal1-body">
                <p>One fine body&hellip;</p>
            </div>
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
            </div>
        </div>
    </div>
</div>

<!-- FileUpload -->
<link href="~/Content/css/jquery.fileupload.css" rel="stylesheet" />
<script src="~/Scripts/fileUpload/jquery.ui.widget.js"></script>
<script src="~/Scripts/fileUpload/jquery.fileupload.js"></script>

<script>
    $(document).ready(function () {
        FileUpload2('fileupload', 'FileID', 'progress1', 'file_name1', 'myModal1', 'arq1', 'trash1', 'NomeOriginal1');
    });
</script>
<!-- /FileUpload -->

<script>
    function visualizar(arquivo, extensao, nome_original) {
        if ('.jpeg|.JPEG|.jpg|.JPG|.png|.PNG|.bmp|.BMP'.indexOf(extensao.toLowerCase()) >= 0)
            $('#myModal1-body').html('<img src="@path' + arquivo + '" class="img-responsive" alt="Responsive image" style="height: 600px">');
        else if (extensao.toLowerCase() == '.pdf')
            $('#myModal1-body').html('<iframe style="height: 600px; width: 100%" src="@path' + arquivo + '"></iframe>');

        $('#myModalLabel').text(nome_original);
    }
</script>

dwm-condominios/Views/Documentos/ListParam.cshtml
@using App_Dominio.Models
@model System.Web.Mvc.PagedList<DWM.Models.Repositories.ArquivoViewModel>
@{
    Layout = null;
}
@if (Model != null)
{
    <div class="dashboard-widget-content">
        <p>
            Clique nos botões de <code>Ação</code> para executar a ação desejada
            <a href="../Documentos/Create" class="text-primary">Incluir</a>
        </p>
        <div class="table-responsive">
            <table class="table table-striped jambo_table bulk_action">
                <thead>
                    <tr class="headings">
                        <th class="column-title text-center nobr">Ação</th>
                        <th class="column-title">Data</th>
                        <th class="column-title text-left">Arquivo</th>
                        <th class="column-title text-left">Edificação</th>
                        <th class="column-title text-center">Unidade</th>
                        <th class="column-title text-left">Condômino</th>
                        <th class="column-title text-left">Grupo</th>
                        <th class="column-title text-center">Sempre Visível</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (DWM.Models.Repositories.ArquivoViewModel download in Model)
                    {
                        <tr class="even pointer">
                            <td class="text-center">
                                <a href="Edit?FileID=@download.FileID" title="Editar"><i class="fa fa-edit fa-2x"></i></a>&nbsp;
                                <a href="Delete?FileID=@download.FileID" title="Excluir"><i class="fa fa-trash fa-2x"></i></a>&nbsp;
                                <a href="@download.MapFile().Replace("~","..")" title="Download" target="_blank"><i class="fa fa-download fa-2x"></i></a>
                            </td>
                            <td>
                                <span>@download.Data</span>
                            </td>
                            <td>
                                <span>@download.Nome</span>
                            </td>
                            <td>
                                <span>@download.EdificacaoDescricao</span>
                            </td>
                            <td>
                                <span class="text-center">@download.UnidadeID</span>
                            </td>
                            <td>
                                <span>@download.CondominoNome</span>
                            </td>
                            <td>
                                <span>@download.GrupoCondominoDescricao</span>
                            </td>
                            <td class="text-center">
                                @if (download.IndSempreVisivel == "S")
                                {
                                    <span class="label label-default">Sim</span>
                                }
                                else
                                {
                                    <span>Não</span>
                                }

                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        @Html.Partial("Paginacao", Model)
    </div>
}
else
{
    @Html.Partial("_AcessoNegadoModal")
}